# Generated by Django 5.1.3 on 2025-05-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='category',
            field=models.CharField(choices=[('Salary', 'Salary'), ('Freelance', 'Freelance'), ('Gift', 'Gift'), ('Business', 'Business_Income'), ('Investment', 'Investment_Income'), ('Rental', 'Rental_Income'), ('Interest', 'Interest'), ('Others', 'Others')], default='Other', max_length=50),
        ),
    ]
