# Generated by Django 5.1.3 on 2025-06-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0003_alter_budget_category_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.CharField(choices=[('Employment', 'Employment'), ('SideHustle', 'SideHustle'), ('Dividend', 'Dividend'), ('Others', 'Others')], default='Other', max_length=50),
        ),
    ]
